### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by KirstenSchuhmann** [KirstenSchuhmann/CapstoneProject#1]
## Value Proposition

**As a User** 

**I want an App** 
to add a plan for my gym workout

**to be able to:**
- see my current gym plan

## Description
![image](https://user-images.githubusercontent.com/115224131/207018666-c060bdb2-1d21-4e5c-9530-17d508ef56da.png)

## Acceptance Criteria

- [ ] Page which has all the Criteria to do a Powerlifting Workout, which includes: 
- [ ] Warm-Up 
- [ ] Main lifts, such as Squat, Bench, Deadlift 
- [ ] Assistant exercise to optimize
- [ ] Each Part has it's own box and set, to differ them apart. 

## Tasks

(for developers team)
- [ ] First: Set Up Project, Structure of Project 
- [ ] Set-Up feature branch: feature/Gym-Plan
- [ ] Add Repository in Github & deploy it on vercel
- [ ] Add Footer Part
- [ ] Add Headline, for each exercise part a section & Headline for the section. 
- [ ] Each section has: 
      - 2x counter -> min. 0 (Set & Reps)
      - input field type: text (for the name of the exercise)
      - input field type: number (to track the weight of the lift)

**Comment by KirstenSchuhmann** [comment]
Hi Antje, 
den Dummy habe ich jetzt einfach mal vorprogrammiert, vielleicht ist das damit mehr ersichtlicher, wie der Plan dann aussehen soll:  https://capstone-project-ow1093qg6-kirstenschuhmann.vercel.app/

Die Input Fields habe ich so erstellt, dass diese schonmal benutzbar sind und ich in dem Fall keine Div's benutzen muss.
