### ISSUE TITLE
Add Input to set Name for Gym Plan

### ISSUE THREAD

**Issue by KirstenSchuhmann** [KirstenSchuhmann/CapstoneProject#14]
## Value Proposition

**As a User** 
**I want an App:** to have an app for my Powerlifting Workout. 
**to be able to:** to add a name to my Gym Plan, to distinguish the saved plans later with the name.

## Description
![Image](https://user-images.githubusercontent.com/115224131/211215588-04f87827-4153-4445-9aa5-1a27d38346bb.png)

## Acceptance Criteria

- [ ] The user can set a name for the gym plan.
- [ ] The user can set notes for the gym plan. 

## Tasks

(for developers team)
- [ ] add input field type text & adjust Styling. 
- [ ] add input field type text & adjust Styling.

**Comment by NeeleWaehnke** [comment]
Hey Kirsten, sieht gut aus :) Bei den Tasks hast du 2mal die gleiche Aufgabe stehen, wahrscheinlich meinst du einmal den Input für den Title und einmal für die Notes, richtig? Das könntest du noch anpassen. 
Ich würde auch noch festlegen, wie oder wo die Notes dann angezeigt werden, z.B sind die Notizen immer sichtbar auf derselben Seite wie die Übungen oder sind sie aufklappbar etc.

**Comment by KirstenSchuhmann** [comment]
Hi Neele :) 
Danke für deinen Input. Ja, ich glaube das definiere ich nochmal genauer, um den Kontext der Input Felder besser zu verstehen. 
Im Prinzip soll jeder Trainingsplan einen Titel haben, z.B. "Legday" und man soll je Trainingsplan Notizen hinzufügen können, wenn man z.B. etwas beachten sollte (z.Bsp. "Fokus Quadriceps, Übungen Unilateral durchführen")
