### ISSUE TITLE
Outsource Code "Create Gym Plan" => Static Page

### ISSUE THREAD

**Issue by KirstenSchuhmann** [KirstenSchuhmann/CapstoneProject#15]
## Value Proposition

**As a User** 
**I want** on my App a button, which leads me to a page, where I can create my own training plans.... 
... and **to be able to** save them, so I can see them later on my main page as sub-pages, to have multiple training plans for different training days. 

## Description

![Bildschirm­foto 2023-01-09 um 15 43 41](https://user-images.githubusercontent.com/115224131/211334865-bf77413c-d092-4f32-991a-b2e2723218a4.png)

## Acceptance Criteria

- [x] Footer has now 2 Links, one leads to main page, one to the page, to create a plan. 
- [x] The created plan can be saved & creates a new page, which will be seen as preview on the main page. 
- [x] The user can save the plan & the plan will be saved, on a second page. 

## Tasks

(for developers team
- [x] add Logo to the main page. 
- [x] add to the footer a <nav> element & set-up two links, while the training emoji leads to "Create Plan" and the logo leads to the main page. 
- [x] add "SaveButton" to "GymPlan.js"
- [x] Create a page, which will be the "Create your Gym Plan" Page. 
- [x] Use component CreateWorkoutRoutineForm.js to add it in the "Create-Workout-Routine.js" file
- [x] Create file for dynamic Routing for the created Gym Plans. 
- [x] The created Gym Plans, will be seen as preview on the main page.
- [x] use localStorage Hook, so user can save data in local Storage

**Comment by andy-schwedler** [comment]
> I want an App: to have an app for my Powerlifting Workout

same here, please provide more context such as - e.g. 
**As a** User
**I want** to have different training plans
**to be able** to create different plans for different training days.

**Comment by KirstenSchuhmann** [comment]
> > I want an App: to have an app for my Powerlifting Workout
> 
> same here, please provide more context such as - e.g. **As a** User **I want** to have different training plans **to be able** to create different plans for different training days.

Thank you for your suggestions! I've updated & included your suggestion in my new value proposition.

**Comment by ufelgen** [comment]
Hi, nur ein kleiner Punkt ist mir aufgefallen: in deinem Scribble hast du auf der "create plan" page in deinem Footer nur ein Icon, das aber da hinführen soll, wo man schon ist (so wie ich das verstanden habe). Da wäre es sinnvoll, das Logo mit reinzumachen, das auf die Hauptseite zurück führt. 
Du kannst auch überlegen, ob du den Footer dynamisch machst, so dass er das Icon mit dem Link zu der Seite, auf der man sich gerade befindet, nicht anzeigt.

**Comment by KirstenSchuhmann** [comment]
Hi Ulli, 
guter Punkt! Mir ist dann noch eingefallen, dass ich das Lifting Emoji doch nicht ganz so passend empfinde für die "Create Gym Plan Page", weshalb ich das jetzt auf das ✚ abgeändert habe :) 
Glaube das ergibt mehr Sinn.
