### ISSUE TITLE
Add "Start Workout" Button to "Created / Saved Gym Plan"

### ISSUE THREAD

**Issue by KirstenSchuhmann** [KirstenSchuhmann/CapstoneProject#16]
## Value Proposition

**As a User** 
**I want an App:** to have an app for my Powerlifting Workout
**to be able to:** to create my own Training plan & save it in the app. 

## Description

![Image](https://user-images.githubusercontent.com/115224131/211220328-eb9e9350-6a6d-4780-a82c-510f23f7a186.png)

![Image](https://user-images.githubusercontent.com/115224131/211220437-4c01e272-3071-465b-ac9b-cee526940002.png)

## Acceptance Criteria

- [ ] The user is able to view plan. 
- [ ] If a plan is opened as page, the use can start a workout. 
- [ ] "start workout" opens up a new page for the training. 
- [ ] "finished workout" stores the data on page "accomplished workouts". 
- [ ] The "Training Page" has all the functionality of the component "Gym Plan". 

## Tasks

(for developers team
- [ ] add "start workout" button 
- [ ] add functionality to "start workout" button, so it leads to new created page "Training" 
- [ ] Training Page has all the functionality of the "create Gym Plan" ( Delete / Add Section / ExerciseSet)
- [ ] add current data to the Training Page
- [ ] add " finish workout" button, so the data will be saved at "accomplished Training / Workouts"
- [ ] set up the page "Accomplished Workouts" & add Link to the Nav Element in Footer

**Comment by julialoeschel** [comment]
Hey Kirsten, 
This US is way too big, start way smaller and divide the Tasks in small pieces. 

have a page per plan dynamically is one US, 
add a new plan could be the next, 
edit and delete plans the third. 
Accomplished workouts another US and so on and so on.

Also usually you dont write the technical Details in your scribble.
Only the screens. If you must, you can include arrows. 

the features are good, 
make it smaller and go for it :)
