### ISSUE TITLE
Add Functionality for dynamic "Created / Saved Plan" Page

### ISSUE THREAD

**Issue by KirstenSchuhmann** [KirstenSchuhmann/CapstoneProject#17]
## Value Proposition

**As a User** 
**I want an App:** to have an app for my Powerlifting Workout
**to be able to:** to create my own Training plan & save it in the app. 

## Description
![Image](https://user-images.githubusercontent.com/115224131/211219524-19656d10-8226-4534-a163-a5ff45e7e27d.png)

## Acceptance Criteria

- [ ] The user is able to edit the plan. 
- [ ] The "Edit" Function shows the buttons to delete / add sections / exerciseSet. 

## Tasks

(for developers team
- [ ] toggle the Visibility of Delete / Add Section / ExerciseSet Functions to the "Edit" Function.
