### ISSUE TITLE
Add Page to directly start with a workout

### ISSUE THREAD

**Issue by KirstenSchuhmann** [KirstenSchuhmann/CapstoneProject#18]
## Value Proposition

**As a User** 
**I want an App:** to have an app for my Powerlifting Workout, to set up my Gym Plan. 
**to be able to:** use my Gym Plan for my Training, but also to be able to start training directly without a plan. 

## Description
..... still empty. 

## Acceptance Criteria

- [ ] Page, so the user can start directly with it's training without a plan. 

## Tasks

(for developers team
- [ ] add to nav a link, which leads to page, where the user can start directly with a training. 
- [ ] the "finished training" button saves the data & stores them on "accomplished Workout"
