### ISSUE TITLE
US #2 - Add "+ Add Exercise" Button. 

### ISSUE THREAD

**Issue by KirstenSchuhmann** [KirstenSchuhmann/CapstoneProject#2]
## Value Proposition

**As a User** 

**I want an App** 
to see my current gym plan for a powerlifting workout. 

**to be able to:**
- add exercises to my plan. 

## Description
![image](https://user-images.githubusercontent.com/115224131/207019921-62f50c08-878b-4e42-9acf-d2aff4456706.png)

## Acceptance Criteria

- [ ] Each Section get's a button, which duplicates the Set above, but without values. 

## Tasks

(for developers team)
- [ ] Use new branch, to for the "+ Add Exercise Button" 
- [ ] Duplicate the Set above, with one of the array methods.

**Comment by KirstenSchuhmann** [comment]
Ja genau, in dieser US sollen die Input-Felder (Set, Exercise, Weight) direkt unter der ersten Exercise ergänzt werden, allerdings ohne Daten, so dass man eine neue Übung im Textfeld hineinschreiben kann.
