### ISSUE TITLE
US #3 - Add "+ Set" Button

### ISSUE THREAD

**Issue by KirstenSchuhmann** [KirstenSchuhmann/CapstoneProject#3]
## Value Proposition

**As a User** 

**I want an App** 
- to see my current gym plan. 

**to be able to:**
- 

## Description
![image](https://user-images.githubusercontent.com/115224131/207025241-ded3207a-853b-4580-85a1-a83241dfce18.png)

## Acceptance Criteria

- [ ] Page has Buttons to add each Exercise Part as section. 
- [ ] Each Section (Warm-Up, Squat, Bench, Deadlift, Assistant) has 3 parts: 
- Set 
- "+ Set" Button
- "+ Add Exercise" Button 

## Tasks

(for developers team)
- [ ] Use new branch, to add the "+ Set" Button
- [ ] Add "+ Set" Button. 
- [ ] The set button copies the values of the set values and makes a copy of them right beneath the copied set.

**Comment by marvinRoellecke** [comment]
Kirsten, your illustrations are very nice and easy to understand.
I don't understand why you want to duplicate and existing exercise? To use it as a template and then modify it?

**Comment by KirstenSchuhmann** [comment]
Thank you, Marvin! :) 

Yes, sometimes, if the set needs to be splitted, it's nice to have the option to copy the first values, so the user doesn't need to spend time to add all the values (set, exercise, weight) again and only needs to change one value.
