### ISSUE TITLE
Add Buttons for each section (Warm-Up, Add Squat...)

### ISSUE THREAD

**Issue by KirstenSchuhmann** [KirstenSchuhmann/CapstoneProject#4]
## Value Proposition

**As a User** 

**I want an App: ** to have an app for my Powerlifting Workout. 

**to be able to:**  to adjust my plan, to which will be done for the day. 

## Description
![Image](https://user-images.githubusercontent.com/115224131/210807887-c1a2b097-a665-4215-9801-9cb9f61d2b47.png)

## Acceptance Criteria

- [x] Button: Add warm-up
- [x] Button: Add Squat
- [x] Button: Add bench
- [x] Button: Add assistant
- [x] Each button should add each section part. 

## Tasks

(for developers team)
- [x] Add all the buttons, for each section. 
- [x] The Data of the Gym should be able to be rendered. -> Update handleSubmit Function
