### ISSUE TITLE
US #5 - Add Delete Button for the section

### ISSUE THREAD

**Issue by KirstenSchuhmann** [KirstenSchuhmann/CapstoneProject#5]
## Value Proposition

**As a User** of my **Training App**
**I want to be able to** delete a section (Warm-Up, Squat, Bench, Deadlift, Assistant). 

## Description
![Image](https://user-images.githubusercontent.com/115224131/210757524-5503a424-e7fe-4b43-9e25-7c6e9e10508c.png)

## Acceptance Criteria

- [x] Each Section (Warm-Up, Squat, Bench, Deadlift, Assistant) has a delete button. 
- [x] Each Section is able to be deleted by clicking on the " x " button in the right corner. 

## Tasks

(for developers team)
- [x] implement the delete button for each section. 
- [x] add a function to the button, which is deleting the corresponding section.
