### ISSUE TITLE
Add delete Button for "set" Part

### ISSUE THREAD

**Issue by KirstenSchuhmann** [KirstenSchuhmann/CapstoneProject#6]
## Value Proposition

**As a User** of a **gym app,** where I can include my main training & ExerciseSets, which I can add via click on the corresponding buttons for each section, 
-> I also need **to be able to** delete an ExerciseSet. 

## Description
![Bildschirm­foto 2023-01-10 um 13 52 59](https://user-images.githubusercontent.com/115224131/211556762-abc1476b-c2ae-47ad-9b32-b9ae10ca1302.png)

## Acceptance Criteria

- [x] show delete button, when set will be swiped to the left. 

## Tasks

(for developers team)
- [x] each set will have a swipe function.
- [x] set can be swiped to the left & keep in place => sticks to the position. 
- [x] while in swiped position, the delete button will be shown. 
- [x] click on delete button = deletes the set.

**Comment by andy-schwedler** [comment]
> I want an App: to have an app for my Powerlifting Workout.

Please describe in more detail, what your users want from this UserStory - e.g. want a button that deletes the current set

**Comment by ufelgen** [comment]
Hi Kirsten, das ist eine gute und übersichtliche User Story! Ich glaube, was Andy meinte war in etwa sowas: 
**As a** user
**I want to** be able to delete an exercise set 
**so that** I can modify my training plan as needed. 
wir hatten ja dieses Template bekommen, wo das so vorgegeben ist. Das Hinzufügen, das du gerade in deiner Value Proposition stehen hast, ist ja nicht Teil dieser User Story, so wie ich das verstanden habe...
